### PR TITLE
cmd/commands: add PostgresSQL DB port, statement_cache_mode config opt

### PR DESCRIPTION
**Pull request by tmszi**
~I tried to deploy GISQUICK web application on the Digital Ocean Kubernetes k8 with success. It would be usefull if some of the configuration settings options were retrieved from the ENV vars.~

### CODE REVIEW

**Comment by marcel-dancak** [comment]
And it doesn't work without your changes? Because used [library](https://pkg.go.dev/github.com/ardanlabs/conf/v2) provides support for using environmental variables and command line arguments for configuration. ENV flag is just for overriding the default variable name. And Gisquick Docker Compose deployment use environmental variables for its configuration.

The only real change I see is a new Port parameter in Postgres config, but this should be already possible to specify in the Host parameter.

**Comment by tmszi** [comment]
> And it doesn't work without your changes? Because used [library](https://pkg.go.dev/github.com/ardanlabs/conf/v2) provides support for using environmental variables and command line arguments for configuration. ENV flag is just for overriding the default variable name. 

No it doesn't work with these default variables values (deployed on Kubernetes). I use custom PostgreSQL DB host, username, port, ssl_mode, dbname, password value ,Redis broker address, QGIS Server address. And that is the reason why I opened this PR.

> And Gisquick Docker Compose deployment use environmental variables for its configuration.

Yes, you are right some ENVs are declared inside generated docker-compose.yml file, but they are not used by server code (doesn't override default config var values).

Steps to reproduce:

1. `git clone https://github.com/gisquick/gisquick-server-next.git`
2. Check if some ENVs override default config var values

```
for i in POSTGRES_USER POSTGRES_PASSWORD POSTGRES_SSL_MODE POSTGRES_HOST GISQUICK_LANGUAGE GISQUICK_SIGNUP_API AUTH_SESSION_EXPIRATION; do grep -Rn $i gisquick-server-next/; done
```

**Comment by tmszi** [comment]
Another useful PostgreSQL DB connection option is `statement_cache_mode`  (`statement_cache_mode=prepare`) which should be overided by ENV `POSTGRES_STATEMENT_CACHE_MODE` especialy in the case when you want use PostgreSQL DB with connection pooler (PgBouncer). In my usecase I use PG DB connection pooler by default `statement_cache_mode=describe`. https://github.com/gisquick/gisquick-server-next/pull/3/commits/e942e6a0f6bb742b92f439d21428a0e62a81f698

Without this PG DB option `statement_cache_mode=describe`  ([doc](https://pkg.go.dev/github.com/jackc/pgx/v4#ParseConfig)) Go Lang PostgreSQL Driver and Toolkit `pgx` module produce error `ERROR: prepared statement "lrupsc_1_6" already exists (SQLSTATE 42P05)` if you use PG DB connection pooler.

**Comment by tmszi** [comment]
But yes of course without these custom values, by default GISQUICK server works as expected and nothing needs to be changed.

**Comment by marcel-dancak** [comment]
I still think there is misunderstanding about env flag. There should be no difference in this definitions
`Postgres struct {
	User string `conf:"default:postgres"`
}`
and
`Postgres struct {
	User string `conf:"default:postgres,env:POSTGRES_USER"`
}`

In both cases, environment variable should be POSTGRES_USER. That's how used library should work. ENV flag is useful only to define different name than what would be generated based on structure/field name.

If you have compiled binary file, you can check names of environment variables with
`<binaryfile> serve --help`

And if you need to verify runtime values, you can check logs. When server starts, it prints startup configuration.

I can check POSTGRES_STATEMENT_CACHE_MODE, but first let's resolve environment variables

**Comment by marcel-dancak** [comment]
Just last question before merging. I don't have any strong opinion about port parameter. I didn't create separate parameter just because it was a little bit less of code to have only host parameter, which can contain also port. Just for curiosity, is it better/easier in Kubernetes deployment to have them separated?

**Comment by tmszi** [comment]
> Just last question before merging. I don't have any strong opinion about port parameter. I didn't create separate parameter just because it was a little bit less of code to have only host parameter, which can contain also port. Just for curiosity, is it better/easier in Kubernetes deployment to have them separated?

I understand, but the reason I made `POSTGRES_PORT` ENV a separate config var is because it's a much more "common" way to define a PostgreSQL DB connection. I have deployed other Python/Django/Java applications which use same config connection schema (separate connection params including port) to connect to PostgreSQL DB .

My Kubernetes secret config manifest yaml file looks like:

```
apiVersion: v1
kind: Secret
metadata:
  name: gisquick-access
type: Opaque
stringData:
  AUTH_SECRET_KEY: ""
  POSTGRES_HOST: ""
  POSTGRES_DB: ""
  POSTGRES_USER: ""
  POSTGRES_PASSWORD: ""
  POSTGRES_PORT: "25061"
  POSTGRES_SSL_MODE: "require"
  POSTGRES_STATEMENT_CACHE_MODE: "describe"
  REDIS_ADDR: "gisquick-redis-broker:6379"
```

But I'm completely ok with default port definition inside `POSTGRES_HOST=mydbhost:mydbport` ENV. Should I revert the port definition changes?

**Comment by marcel-dancak** [comment]
If it's a more common way, lets keep this change. There is a little chance that it will break someones deployment, but that is also true for other breaking changes which is sometimes needed to do. And it's good to know it's working on Kubernetes, even though I'm still hesitating to learn this technology.

**Pull request merged**
